### ISSUE TITLE
Which usb network card to use? 

### ISSUE THREAD

**Issue by zhangxiaofan1992** [PGBSean/Surface-Pro-5-OpenCore#11]
Which usb network card to use? Online sales only support 10.14-10.15，Which USB network card did you buy? Please tell me the specific model.

**Comment by PGBSean** [comment]
For USB Wi-Fi adapter, refer to [this list](https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter?tab=readme-ov-file#%EF%B8%8E---known-working-and-testing-adapter)

For miscellaneous adapters (PCIe, mSATA, etc.), [here](https://dortania.github.io/Wireless-Buyers-Guide/)

Please do not follow the vendor's compatibility list, as macOS do not support 32-bit applications from macOS 10.15 Catalina and above.

**Comment by zhangxiaofan1992** [comment]
Thank you so much，In addition, I would like to ask, I also have 13.6.1 installed on the device, but the touch screen does not work. I do not have the original keyboard. Is this the reason?

**Comment by PGBSean** [comment]
Touch screen support does not have to do with the keyboard.

To gain touch screen support, you need to install a bash script (https://github.com/Xiashangning/IPTSDaemon)

**Comment by zhangxiaofan1992** [comment]
Thank you very much for your support, I have installed it successfully
