### ISSUE TITLE
Older versions of Typing Folio Not working

### ISSUE THREAD

**Issue by Thomas20090425** [PGBSean/Surface-Pro-5-OpenCore#5]
During the process of installation, the typing folio isnt workingwhich means no trackpad or keyboard. Problem present in all of the os below.

os(Tried to install): Sonoma, Monterey, Ventura, Big Sur
Device: i5, 8+256
USB: 128GB
Installation media created by a macbook pro using official mac installation app

**Comment by Thomas20090425** [comment]
Neither works after the installation, tried a few debugging with BigSurface's GitHub, still no luck. Other than that, everything else works, really appreciate it.

:/

**Comment by Thomas20090425** [comment]
Update on my side,

it had been discovered that the machine I’m using, the keyboard was replaced with a 3’s keyboard instead of using a 5’s keyboard. Trying to figure out a workaround, I’ll keep you guys updated, any help is appreciated.

**Comment by PGBSean** [comment]
I would recommend that you use the correct keyboard for the right model, but it seems like that the SP3's keyboard might as well work in the Pro 5 (5 pins config)

This could either that your Pro 5 keyboard is faulty, or there is a USB mapping issue with the existing one in the EFI. **I'd recommend you re-map the USBs by yourself**

You may comment more about this, or close right away, thanks!

**Comment by Thomas20090425** [comment]
That is a great idea, thanks and I’ll try.

I can tell it is something wrong about USB, the keyboard actually will work for a while when in macOS installer, when the installer hasn’t finished booting and have only an Apple logo, the keyboard & mouse works. But right after booting, the system simply said no.

I checked Hackintools, it seems like each time the Typing Folio receives an input, it just decides to disconnect it self and reconnect a second after, therefore the keyboard backlight blinks.

Remapping the USB port seems like a good approach, thank you. I’ll keep this issue updated

**Comment by Thomas20090425** [comment]
Updated [https://drive.tjokas.com/f/7RuQ/IMG_0522.mov](video) demonstrating the problem.

**Comment by Thomas20090425** [comment]
So after a few searches, from surface 3 pro’s hackintosh efi, this seems to be a problem with keyboard versions 16xx in general, can’t be fixed, so this might be a CNP, best choice is to buy a new keyboard.
