### ISSUE TITLE
Micro SD card not working

### ISSUE THREAD

**Issue by Thomas20090425** [PGBSean/Surface-Pro-5-OpenCore#6]
Tested with a micro SD card with 8GB of storage and an sd card with 1TB of storage, both are not recognized.

**Comment by PGBSean** [comment]
I'll be looking forward to that.

**Comment by PGBSean** [comment]
Although I did tried `EmeraldSDHC.kext` for the EFI, it did not work for the microSD slot.

Looking further into the issue I found that none of the past Hackintoshers actually get the microSD slot to work on macOS, and is required to add more configs to the USB mappings.

You may comment more about this or close right away, thanks!

**Comment by Thomas20090425** [comment]
I’ll still try to work on this in the future, surface pro 7 and pro 5 should be similar, since they got pro 7’s SD card to work, I’ll keep this updated, for the mean time, I’ll close this issue, since it doesn’t affect much.

**Comment by PGBSean** [comment]
Great news!

Looking at @jlempen's [Surface-Go-2-OpenCore](https://github.com/jlempen/Surface-Go-2-OpenCore), I managed to add support for the microSD slot.

You may expect this update later once I test this kext, thanks!

**Comment by Thomas20090425** [comment]
Great to hear that!

Happy to test, looking forward to it!

**Comment by PGBSean** [comment]
[EFI.zip](https://github.com/PGBSean/Surface-Pro-5-OpenCore/files/15211643/EFI.zip)
You may try the EFI above and check whether if it's working or not, **as it does not work on my side**

Please note that I added some additional kexts that may not necessary to you but will not affect your workload.

**Comment by Thomas20090425** [comment]
No problem,

random thought, will it have anything to do with remapping the usb? Maybe
the kext is trying to emulate the SD card reader as a usb line? I don’t
have the device available currently, I’ll try tomorrow!

Thanks

**Comment by PGBSean** [comment]
I have fixed it and published the modified EFI to production. This should work now, thanks!

**Comment by Thomas20090425** [comment]
Sweet, everything works now!
One small problem tho… The efi no longer detects windows installs.

**Comment by Thomas20090425** [comment]
That was my problem. Accidentally deleted Windows’s partition.
