### ISSUE TITLE
Any issues other than Camera, Windows Hello, Wifi & BT which are mentioned in the listing? 

### ISSUE THREAD

**Issue by alappatsj** [PGBSean/Surface-Pro-5-OpenCore#9]
Any issues other than Camera, Windows Hello, Wifi & BT which are mentioned in the listing?  The same EFI work for Core i7 - 8 GB RAM model (SP5) as well ? Is it good for daily usage, I mean as main device?

Any guide for installation?

Thank You very much in Advance.

**Comment by alappatsj** [comment]
Thank you very much for detailed response.

I had Monterey installation USB ready for SP3 & SP4, and I have replaced the EFI with yours. 

The installation was little easy. But the 1st boot or setup is giving issues. Hangs either at Hello or Language selection and it cannot go past selecting country or region.    Even after multiple reboots, cannot go past select your country page. 

My device is Surface Pro 5 CORE * i7 * , 8 GB RAM. So any issues with graphics? 

Plz help

**Comment by PGBSean** [comment]
From my knowledge, Surface Pro 5 i7 models have a different graphics model than the base model. You need to edit the graphics value in DeviceProperties in config.plist to the supported GPU on your machine.

You may get pre-made samples [here](https://github.com/5T33Z0/OC-Little-Translated/blob/main/11_Graphics/iGPU/iGPU_DeviceProperties.md)

Thanks for your support!

**Comment by alappatsj** [comment]
I changed the Deviceproperties for device id & platform id for iris 640 mentioned in the dortania display config article. And now I can boot & I had multiple manual restarts. So for now, it seems to be working fine. Thank you very much. Now the issue is, ny external hard disk is not accessable neither on macos nor on windows. It is showing in device list in both devices, but unable to access the files. My entire backup (files) is in it. I know it is off topic, but your experience can help me in this

**Comment by PGBSean** [comment]
If both macOS and Windows cannot read the drive, then it's a drive issue. You may use recovery software, or worse, erase the drive.

Honorable mention: The drive might be readable in Linux, but that is zero chance of happening.
